### ISSUE TITLE
Dr. Reflex

### ISSUE THREAD

**Issue by CashSpareChange** [Fasguy/BaldisBasicsModMenu-archive#103]
If possible, it would be cool if you could import Dr. Reflex into the mod menu via the BB+ files. Giving him his own room would be cool too, however it might be kinda hard since he isn't already hardcoded into the game like Mrs. Pomp is. If you don't add him, it's ok! After all, this is just a suggestion lol.

**Comment by Fasguy** [comment]
That's a mod for someone else to make, I'm not gonna add this into the ModMenu directly. Sorry.
