### ISSUE TITLE
Game won't open

### ISSUE THREAD

**Issue by astro1354** [Fasguy/BaldisBasicsModMenu-archive#105]
**What's the Version of the game you're using?**
Playing the classic game, v1.4.3 with the mod menu

**What's the Version of the mod you're using?**
2.0.2

**What Operating System are you using?**
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)
Windows 10 64 bit

**Describe the bug**
For some reason it won't let me past the warning screen even if i press a button

**Comment by Fasguy** [comment]
If you hit Ctrl+Backspace, it should open the Problem Trace Console. Please send me any errors that might be shown there.

**Comment by astro1354** [comment]
![image](https://github.com/Fasguy/BaldisBasicsModMenu-archive/assets/107153596/134b0204-6f6a-41c1-8f55-3866619cd039)

**Comment by astro1354** [comment]
the red text is a bit hard to read but it says junk about the unity engine and objects n stuff. i'm no coding expert so idk

**Comment by Fasguy** [comment]
Your ModMenu config is corrupted.
Go to `C:\Users\<Your Windows Username>\AppData\LocalLow\Basically Games\Baldi's Basics Classic\FasguyMods\ModMenu` and deleted the config.json file

**Comment by astro1354** [comment]
yooo it worked thank you sm
