### ISSUE TITLE
heres the player.log file

### ISSUE THREAD

**Issue by waleve2009** [Fasguy/BaldisBasicsModMenu-archive#107]
<details>
  <summary>Player.log</summary>

Mono path[0] = 'C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Managed'
Mono config path = 'C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/MonoBleedingEdge/etc'
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/lib/usr/lib/libSystem.dylib
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/lib/usr/lib/libSystem.dylib.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/lib/usr/lib/libSystem.dylib
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libc.so.6
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libc.so.6.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libc.so.6
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69296DF0.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69719500.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF696F9AF0.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69035180.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69036190.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF697188F0.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF690371A0.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF690381B0.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF697170D0.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF6903A1D0.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69717CE0.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF6903B1E0.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF6971A110.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69A8D4E0.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF696FE320.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF699F4D70.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF699F2940.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69A95560.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69A94550.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF699F4160.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69A96570.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69A8F500.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF699F1D30.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69A90510.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69A97580.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF699F1120.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69A98590.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69A92530.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF699EE0E0.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF69A91520.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/data-000001FF6D6F6040.dll
Initialize engine version: 2020.3.38f1 (8f5fde82e2dc)
[Subsystems] Discovering subsystems at path C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: AMD Radeon R7 Graphics (ID=0x9874)
    Vendor:   
    VRAM:     3805 MB
    Driver:   27.20.1034.6
Begin MonoManager ReloadAssembly
- Completed reload, in  0.148 seconds
<RI> Initializing input.

XInput1_3.dll not found. Trying XInput9_1_0.dll instead...
<RI> Input initialized.

D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initialized touch support.

UnloadTime: 1.248600 ms
[Message:   BepInEx] BepInEx 5.4.22.0 - BALDI (3/13/2024 10:14:02 PM)
[Info   :   BepInEx] Running under Unity v2020.3.38.9396190
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 3 plugins to load
[Info   :   BepInEx] Loading [Bepity 1.0.0]
[Error  :   BepInEx] Error loading [Bepity 1.0.0] : 
[Debug  :   BepInEx] System.BadImageFormatException: 
File name: 'C:\Users\Owner\Desktop\Baldi's Basics Classic Remastered\BepInEx\plugins\ModMenu\Bepity.dll'
  at (wrapper managed-to-native) System.Reflection.Assembly.LoadFrom(string,bool)
  at System.Reflection.Assembly.LoadFrom (System.String assemblyFile, System.Security.Policy.Evidence securityEvidence) [0x00000] in <a1e9f114a6e64f4eacb529fc802ec93d>:0 
  at System.Reflection.Assembly.LoadFile (System.String path, System.Security.Policy.Evidence securityEvidence) [0x0002b] in <a1e9f114a6e64f4eacb529fc802ec93d>:0 
  at BepInEx.Preloader.RuntimeFixes.HarmonyInteropFix.LoadFile (System.String path) [0x00000] in <a7e3be82e3634ca29e921a65272c4875>:0 
  at BepInEx.Preloader.RuntimeFixes.HarmonyInteropFix.OnAssemblyLoad (System.Reflection.Assembly& __result, System.String __0) [0x0001d] in <a7e3be82e3634ca29e921a65272c4875>:0 
  at System.Reflection.Assembly.LoadFile (System.String path) [0x00005] in <a1e9f114a6e64f4eacb529fc802ec93d>:0 
  at BepInEx.Bootstrap.Chainloader.Start () [0x006c4] in <5e471ddbeb974684bff43bc61f1b58cb>:0 
[Warning:   BepInEx] Skipping [ModMenu 1.3.0] because it has a dependency that was not loaded. See previous errors for details.
[Info   :   BepInEx] Loading [Classic, Yet Again (ModMenu Plugin) 1.3.0]
[Error  :   BepInEx] Error loading [Classic, Yet Again (ModMenu Plugin) 1.3.0] : 
[Debug  :   BepInEx] System.BadImageFormatException: 
File name: 'C:\Users\Owner\Desktop\Baldi's Basics Classic Remastered\BepInEx\plugins\ModMenu\ClassicYetAgain.dll'
  at (wrapper managed-to-native) System.Reflection.Assembly.LoadFrom(string,bool)
  at System.Reflection.Assembly.LoadFrom (System.String assemblyFile, System.Security.Policy.Evidence securityEvidence) [0x00000] in <a1e9f114a6e64f4eacb529fc802ec93d>:0 
  at System.Reflection.Assembly.LoadFile (System.String path, System.Security.Policy.Evidence securityEvidence) [0x0002b] in <a1e9f114a6e64f4eacb529fc802ec93d>:0 
  at BepInEx.Preloader.RuntimeFixes.HarmonyInteropFix.LoadFile (System.String path) [0x00000] in <a7e3be82e3634ca29e921a65272c4875>:0 
  at BepInEx.Preloader.RuntimeFixes.HarmonyInteropFix.OnAssemblyLoad (System.Reflection.Assembly& __result, System.String __0) [0x0001d] in <a7e3be82e3634ca29e921a65272c4875>:0 
  at System.Reflection.Assembly.LoadFile (System.String path) [0x00005] in <a1e9f114a6e64f4eacb529fc802ec93d>:0 
  at BepInEx.Bootstrap.Chainloader.Start () [0x006c4] in <5e471ddbeb974684bff43bc61f1b58cb>:0 
[Message:   BepInEx] Chainloader startup complete
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_3.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_3.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_3.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_3
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_3.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_3
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libxinput1_3.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libxinput1_3.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libxinput1_3.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_2.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_2.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_2.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_2
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_2.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_2
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libxinput1_2.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libxinput1_2.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libxinput1_2.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_1.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_1.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_1.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_1
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_1.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/xinput1_1
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libxinput1_1.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libxinput1_1.dll
Fallback handler could not load library C:/Users/Owner/Desktop/Baldi's Basics Classic Remastered/BALDI_Data/Mono/libxinput1_1.dll
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
Initializing input management.
Steam Input was not initialized because SteamManager was not initialized.
DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
Save data for file !UnassignedFile loaded successfully!
Save file version = 0
High scores saved.
Config for file !UnassignedFile loaded successfully!
High scores saved.
File progress for !UnassignedFile saved
Config for !UnassignedFile saved
screen size y = 1080
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 4.235300 ms

Unloading 353 unused Assets to reduce memory usage. Loaded Objects now: 2108.
Total: 32.635800 ms (FindLiveObjects: 0.208300 ms CreateObjectMapping: 0.154700 ms MarkObjects: 30.979900 ms  DeleteObjects: 1.292300 ms)

The referenced script on this Behaviour (Game Object 'Canvas') is missing!
Unloading 4 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.671700 ms

Unloading 3 unused Assets to reduce memory usage. Loaded Objects now: 2116.
Total: 42.101100 ms (FindLiveObjects: 0.225200 ms CreateObjectMapping: 0.121700 ms MarkObjects: 41.714400 ms  DeleteObjects: 0.039300 ms)

Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 0.549500 ms

Unloading 9 unused Assets to reduce memory usage. Loaded Objects now: 18576.
Total: 63.452000 ms (FindLiveObjects: 1.248000 ms CreateObjectMapping: 1.699900 ms MarkObjects: 60.292800 ms  DeleteObjects: 0.199000 ms)

High scores saved.
File progress for !UnassignedFile saved
Config for !UnassignedFile saved
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 3.899400 ms
Level loader loading ClassicNullContainer.

Unloading 45 unused Assets to reduce memory usage. Loaded Objects now: 18070.
Total: 80.199800 ms (FindLiveObjects: 1.801000 ms CreateObjectMapping: 2.944800 ms MarkObjects: 75.113600 ms  DeleteObjects: 0.339500 ms)

Level loader initializing level.
Level loader initializing heap.
Heap initialized.
Level loader setting up rooms.
Level loader loading tile data.
Tile data loaded.
Level loader setting room size and position data.
Level loader creating exits.
Level loader building doors.
Level loader building windows.
Level loader setting up room functions.
Level loader calculating open areas.
Level loader blocking tiles marked to be blocked.
Level loader building buttons.
Level loader loading room objects.
Level loader placing items.
Level loader loading tile based objects.
Level loader instantiating object builders.
Level loader loading and generating posters.
Poster TestPoster1 using outdated material. Update to use texture.
Level loader loading and generating light sources.
Level loader loading activities.
Level loader setting up events.
Level loader setting up NPCs to spawn.
Level loader setting NPC spawn points.
Level loader finished loading!
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 22.395900 ms

Unloading 203 unused Assets to reduce memory usage. Loaded Objects now: 18669.
Total: 73.813900 ms (FindLiveObjects: 1.340500 ms CreateObjectMapping: 1.914900 ms MarkObjects: 69.911300 ms  DeleteObjects: 0.646400 ms)

High scores saved.
File progress for !UnassignedFile saved
Config for !UnassignedFile saved
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 3.676300 ms
Level loader loading ClassicNullContainer.

Unloading 138 unused Assets to reduce memory usage. Loaded Objects now: 18070.
Total: 82.802400 ms (FindLiveObjects: 2.260500 ms CreateObjectMapping: 2.142800 ms MarkObjects: 77.687300 ms  DeleteObjects: 0.711000 ms)

Level loader initializing level.
Level loader initializing heap.
Heap initialized.
Level loader setting up rooms.
Level loader loading tile data.
Tile data loaded.
Level loader setting room size and position data.
Level loader creating exits.
Level loader building doors.
Level loader building windows.
Level loader setting up room functions.
Level loader calculating open areas.
Level loader blocking tiles marked to be blocked.
Level loader building buttons.
Level loader loading room objects.
Level loader placing items.
Level loader loading tile based objects.
Level loader instantiating object builders.
Level loader loading and generating posters.
Poster TestPoster1 using outdated material. Update to use texture.
Level loader loading and generating light sources.
Level loader loading activities.
Level loader setting up events.
Level loader setting up NPCs to spawn.
Level loader setting NPC spawn points.
Level loader finished loading!
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 22.772200 ms

Unloading 203 unused Assets to reduce memory usage. Loaded Objects now: 18669.
Total: 76.816700 ms (FindLiveObjects: 1.480300 ms CreateObjectMapping: 1.871400 ms MarkObjects: 73.007100 ms  DeleteObjects: 0.457500 ms)

High scores saved.
File progress for !UnassignedFile saved
Config for !UnassignedFile saved
High scores saved.
File progress for !UnassignedFile saved
Config for !UnassignedFile saved
Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 2.920100 ms
Level loader loading ClassicNullContainer.

Unloading 137 unused Assets to reduce memory usage. Loaded Objects now: 18071.
Total: 66.148100 ms (FindLiveObjects: 1.762500 ms CreateObjectMapping: 3.200100 ms MarkObjects: 60.601700 ms  DeleteObjects: 0.583400 ms)

Level loader initializing level.
Level loader initializing heap.
Heap initialized.
Level loader setting up rooms.
Level loader loading tile data.
Tile data loaded.
Level loader setting room size and position data.
Level loader creating exits.
Level loader building doors.
Level loader building windows.
Level loader setting up room functions.
Level loader calculating open areas.
Level loader blocking tiles marked to be blocked.
Level loader building buttons.
Level loader loading room objects.
Level loader placing items.
Level loader loading tile based objects.
Level loader instantiating object builders.
Level loader loading and generating posters.
Poster TestPoster1 using outdated material. Update to use texture.
Level loader loading and generating light sources.
Level loader loading activities.
Level loader setting up events.
Level loader setting up NPCs to spawn.
Level loader setting NPC spawn points.
Level loader finished loading!
Setting up 2 worker threads for Enlighten.
  Thread -> id: f84 -> priority: 1 
  Thread -> id: da4 -> priority: 1 
</details>

**Comment by Fasguy** [comment]
Looks like the ModMenu got corrupted. Try re-downloading and extracting the ModMenu again.

**Comment by waleve2009** [comment]
> Looks like the ModMenu got corrupted. Try re-downloading and extracting the ModMenu again.

i tried that and removed the other file and added the new one in, went in game clicked tab and nothing popped up. i have no idea why its not working i beat all of the null stuff legitimately and i just wanted to go through it again but without any deaths, is there anything else i can do to try and fix it

**Comment by Fasguy** [comment]
Resolved in YouTube comments.
Copy of the game broke(?)
