### ISSUE TITLE
Can you add a save manager for the BBCR ModMenu?

### ISSUE THREAD

**Issue by SUPERMEATBOY711** [Fasguy/BaldisBasicsModMenu-archive#110]
You can already cheat enough, So why not add achievements access for steam?

So, This feature would work by clicking on player data, then there would be a button to modify original save/or swap saves. The modify original save option would launch your original .sav file, and allow you to unlock achievements, and records for endless. Then you can swap saves anytime if you want. When you select a save file it will reboot your game in your save file.

**Comment by Fasguy** [comment]
A save manager is effectively pointless for CR, as the save mainly holds settings and the other things can now be toggled directly through the ModMenu, when needed.
I don't understand why people want to be able to cheat their achievements so badly. It does literally nothing.
