### ISSUE TITLE
Black Screen No Gameplay

### ISSUE THREAD

**Issue by Skyliner5678** [Fasguy/BaldisBasicsModMenu-archive#112]
**What's the Version of the game you're using?**
1.4.3/1.4.4

**What's the Version of the mod you're using?**
2.0.1/2.0.2

**What Operating System are you using?**
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)
Android Realme8i 64 Bit

**Describe the bug**
Black screen no audio no nothing like at all

**Steps to reproduce the behavior**
Idk

**Expected behavior**
The game would open

**Screenshots**
![Screenshot_2024-03-22-13-58-36-62_d040d37a7aee44824ada277c57069d67](https://github.com/Fasguy/BaldisBasicsModMenu-archive/assets/88817496/8c88b70e-3aaa-482d-9e0f-dcda6c6ad76b)
Uhhh yeah

**Comment by Fasguy** [comment]
See https://github.com/Fasguy/BaldisBasicsModMenu-archive/issues/65#issuecomment-1732958032
