### ISSUE TITLE
Modifiable Cloudy Copter wind force

### ISSUE THREAD

**Issue by mxlouka** [Fasguy/BaldisBasicsModMenu-archive#118]
**Why do you need this feature?**
Mostly because i want to give myself a challenge in Demo Style, as it's far more easier than the other styles, since Baldi's anger doesn't increase as much if you get a question wrong.

**Describe the feature**
Allows the player to change the wind force of Cloudy Copter. Negative values should be allowed to make Cloudy Copter pull you towards him instead of pushing you farther away.

**Comment by Fasguy** [comment]
This modifier already exists.
