### ISSUE TITLE
Can't open cheat menu

### ISSUE THREAD

**Issue by Luchezr** [Fasguy/BaldisBasicsModMenu-archive#121]
**What's the Version of the game you're using?**
1.1

**What's the Version of the mod you're using?**
1.3.0

**What Operating System are you using?**
Windows 10 Pro 64 Bit

**Describe the bug**
Cant open cheat menu, files directory is:
"Game"\BepInEx\plugins\modMenu\"filesfilesfiles"

**Expected behavior**

**Screenshots**
![image](https://github.com/Fasguy/BaldisBasicsModMenu-archive/assets/102498469/e273db2b-97c1-452c-a4a1-75a26ab00fc0)

**Comment by Fasguy** [comment]
Please upload your Player.log file here, so i can investigate this. (`C:\Users\<your Windows user>\AppData\LocalLow\Basically Games\Baldi's Basics Classic Remastered\Player.log`)
