### ISSUE TITLE
help idk how to open whats the button

### ISSUE THREAD

**Issue by Playerfox123** [Fasguy/BaldisBasicsModMenu-archive#122]
**What's the Version of the game you're using?**
latest

**What's the Version of the mod you're using?**
latest

**What Operating System are you using?**
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)
windows 11

**Describe the bug**
not a bug i just dont know the open menu button

**Steps to reproduce the behavior**
forget the button to open it

**Expected behavior**
not able to open menu

**Screenshots**

**Comment by Fasguy** [comment]
Tab.
Also explained in the README.txt file included in the mod's zip file.
