### ISSUE TITLE
Warning Screen Won't Work.

### ISSUE THREAD

**Issue by SpartaVR12** [Fasguy/BaldisBasicsModMenu-archive#124]
**What's the Version of the game you're using?**
1.4.3.

**What's the Version of the mod you're using?**
Classic 1.4.3 Mod Menu.

**What Operating System are you using?**
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)
I'm using Windows 10 Pro 64 Bit.

**Describe the bug**
I installed the 1.4.3 mod menu, when I booted up the BALDI.exe file, I get a warning screen, but when I click on the warning screen to load the title screen, IT WOULDN'T TELEPORT ME TO THE TITLE.

**Steps to reproduce the behavior**
Idk.

**Expected behavior**
I was expecting it to work, but no. It wouldn't.

**Screenshots**
no screenshots.

**Comment by SpartaVR12** [comment]
Nevermind, I fixed it.

I downgraded mod menu version 2.0 to 1.18.2.

**Comment by Fasguy** [comment]
I think the ModMenu just got corrupted when you installed v2.0 initially.
