### ISSUE TITLE
null style not working

### ISSUE THREAD

**Issue by alvar34** [Fasguy/BaldisBasicsModMenu-archive#128]
**What's the Version of the game you're using?**
1.1 

**What's the Version of the mod you're using?**
1.3.0
**What Operating System are you using?** 
windows hp
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)
windows 12 hp 64 bit i guess

**Describe the bug**
when i am during null style the nootebooks that i pick arent working, they just show me the yctp but after that the nootebook is still in the desk and the nootebook counter doesnt count, only in null style

**Steps to reproduce the behavior**
just pick a nootebook in null style

**Expected behavior**
i was thinking the nootebook will disapear and the nootebook counter start working (bad english sorry)

**Screenshots**

**Comment by Fasguy** [comment]
You need to have found the secrets to properly play Null Mode
