### ISSUE TITLE
baldis basics + mod menu pls add this to the archive

### ISSUE THREAD

**Issue by baldiandbonzifan** [Fasguy/BaldisBasicsModMenu-archive#136]
**Why do you need this feature?**
i love ur md menu but since i got baldis basics Plus the modmenu by oldsport SUCKS so thats why

**Describe the feature**
its just like the one on bbcr but  no null and this is the new characters there
dr reflex
the test 
and more
it still has events
so pls i want it
i dont like olsport

**Comment by Fasguy** [comment]
Effective duplicate of #16
