### ISSUE TITLE
does anyone know how you get to awnser the impossible auqstion in baldi's basics classic remastered modmenu?

### ISSUE THREAD

**Issue by dylanytgoat** [Fasguy/BaldisBasicsModMenu-archive#140]
**Why do you need this feature?**
Describe why you're suggesting this feature

**Describe the feature**
A clear and concise description of what the feature is.

**Comment by Fasguy** [comment]
This is a board for bugs and feature suggestions, not general usage questions.
42 answers the impossible question.
