### ISSUE TITLE
Hard Crash with Legion (default settings)

### ISSUE THREAD

**Issue by benjaminpants** [Fasguy/BaldisBasicsModMenu-archive#15]
Enabling Legion without changing any settings freezes the game, the console can still be toggled however.
(I've also tried changing settings, however that seemed to have not fixed anything)
![image](https://user-images.githubusercontent.com/27522994/127759239-ddb483bb-0cb6-4afe-8fc3-d086eccbe77b.png)

**Comment by Fasguy** [comment]
Fixed in commit 7dbc4bc65f4b0cc7f6925b24aa57c2c82bbd5c21
