### ISSUE TITLE
Plus Mod Menu ETA?

### ISSUE THREAD

**Issue by FerdinandoPH** [Fasguy/BaldisBasicsModMenu-archive#16]
I'm looking forward to a mod menu for Baldi's Basics Plus, and I heard you were making one. Do you know when will it be released (more or less)? I really liked the mod menu for the classic Baldi.

**Comment by Fasguy** [comment]
I don't announce ETAs anymore.
The best ways to know when the Plus Mod Menu gets released is to do one of these things:
- "Watch" this repository (a button in the top-right) to get notified, as the Plus Mod Menu versions will also be archived here.
- Subscribe to my YouTube channel to get notified about the Trailer that will release alongside it.
- Manually check this repository/my website/my YouTube channel.

**Comment by FerdinandoPH** [comment]
Ok, thx for the info, I'm glad to know that you're still working on it. Good luck!

**Comment by SomeGDPerson123** [comment]
Just wondering, how's it doing? Also, when do you think a public version could release, even if its an unstable beta?

**Comment by Fasguy** [comment]
> Just wondering, how's it doing? Also, when do you think a public version could release, even if its an unstable beta?

I haven't properly worked on the ModMenu since ~0.3.8, right now it'd be literally unusable.
I don't intend on working on the ModMenu again before 1.0 and with my rapidly declining interest in the game as a whole, it remains to be seen if I'll even be motivated enough to work on the Plus ModMenu at all anymore.

**Comment by v80807707-cpu** [comment]
**💯👎👎👎👎👎
**
