### ISSUE TITLE
Issue on unlocked camera

### ISSUE THREAD

**Issue by BugFinderz** [Fasguy/BaldisBasicsModMenu-archive#17]
on version 2.0.2 when you go on unlocked camera you cannot look down. It is bad for people who likes flying with noclip

**Comment by Fasguy** [comment]
Unfortunately, that's just how the unlocked camera has to work.
The game doesn't have a dedicated MouseY axis anymore, so the only way i can actually check for Y-based mouse movement is by measuring the amount of pixels the mouse moved between frames.

This essentially means, that you just don't have enough wiggle-room towards the bottom of your screen to actually make this workaround possible. The only thing i can suggest is trying to run the game at different resolutions.
