### ISSUE TITLE
Flashlight bug

### ISSUE THREAD

**Issue by ghost** [Fasguy/BaldisBasicsModMenu-archive#18]
**What's the Version of the game you're using?**
1.4.3

**What's the Version of the mod you're using?**
2.0.2

**What Operating System are you using?**
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)
Windows 10 Pro 64bit [21H2]

**Describe the bug**
Flashlight isn't working

**Steps to reproduce the behavior**
1. Turn on flashlight and make school tint dark

**Expected behavior**
A flashlight in the darkness

**Comment by Fasguy** [comment]
Could not reproduce this behaviour.
The flashlight always activated properly, no matter where, when or how i activated it.
If you have any additional information for this behaviour (game logs, videos, screenshots, etc.) then please re-open this issue with them attached.

**Comment by ghost** [comment]
It worked before the factory reset I did when I thought my laptop had bugged out [but it was a switch on the side that fixed the "bug"] so it can't be my graphics driver, I never changed it
https://user-images.githubusercontent.com/101940700/167283135-ce48cb69-3fe9-4a10-a49c-76aac84b4cef.mp4
