### ISSUE TITLE
Issue on decompiled game

### ISSUE THREAD

**Issue by Visualwit** [Fasguy/BaldisBasicsModMenu-archive#20]
**What's the Version of the game you're using?**
1.4.3 (Decompiled By Porky Powers on itch.io)

**What's the Version of the mod you're using?**
2.0.2

**What Operating System are you using?**
Windows 10 Home 64 Bit

**Describe the bug**
I downloaded a decompiled version of baldi's basics classic from "https://porkypowers.itch.io/baldi-open-source-classic-party".
I opened it in Unity and modded a few assets, then once I built the game, I went to install the latest version of the mod menu, and I noticed the "Assembly-CSharp" file was 60KB, and the mod's file was 876KB! But once I installed it, I loaded the game, and now I can't get past the "Warning" Screen! The game is BROKEN!

**Steps to reproduce the behavior**
Built the game through Unity, installed the latest version of the mod menu, can't get past the warning screen.

**Expected behavior**
I expected the game to work with the mod menu installed.

**Screenshots**
![mod](https://user-images.githubusercontent.com/78001651/184506860-9b975e20-20fa-4590-8618-eb8df67643a4.PNG)

**Comment by Fasguy** [comment]
Decompiled versions of the game are and were never supported.

**Comment by Visualwit** [comment]
Alright, I guess i have to decompile a working copy of the game with your mod menu with "AssetRipper" and try to fix all the script errors. :(
