### ISSUE TITLE
Classic Remastered?

### ISSUE THREAD

**Issue by ghost** [Fasguy/BaldisBasicsModMenu-archive#22]
Is there going to be a mod menu for Baldi's Basics Classic Remastered?

**Comment by Fasguy** [comment]
Yes. I'm already working on it.

**Comment by ghost** [comment]
Nice

**Comment by marcoplayz1929** [comment]
will baldi's basic's classic remastered mod menu be for MacBook

**Comment by ghost** [comment]
> will baldi's basic's classic remastered mod menu be for MacBook

I think it will.

**Comment by marcoplayz1929** [comment]
when will it release

**Comment by Fasguy** [comment]
The Mod has been released.
