### ISSUE TITLE
bug report 0555

### ISSUE THREAD

**Issue by ItzExvirnity** [Fasguy/BaldisBasicsModMenu-archive#23]
Baldi's Basics Classic Remastered

baldiclassic1_4_3modmenu2_0_2

Windows 11 Home 64 bit

After starting the game i can only see black screen

I expected that the game will get into the menu of the game

Screenshots here:

![screenshot](https://user-images.githubusercontent.com/118678848/202912163-c8988934-de62-455f-9e88-f50346a619eb.png)

**Comment by Fasguy** [comment]
The mod is not compatible with Classic Remastered, because the underlying codebase is fundamentally different.
[A version for Classic Remastered is still in progress.](https://github.com/Fasguy/BaldisBasicsModMenu-archive/issues/22)
