### ISSUE TITLE
Please?

### ISSUE THREAD

**Issue by Kevinhthegdfan** [Fasguy/BaldisBasicsModMenu-archive#25]
When will you make a mod menu for the BBCCS 5 games? Because the mod menus don't work in  Il2cpp games at all and some versions of BBCCS 5 Have Il2cpp instead of the normal baldi engine or data such as the Mega school version, the Bummus Hummus School version, And the Boldur School version aswell.

**Comment by Fasguy** [comment]
I won't make a ModMenu for decompiles (also discussed in #20). If i made a ModMenu for every decompile, i'd be working on nothing but ModMenus 25/7.

**Comment by Kevinhthegdfan** [comment]
I was trying to say that you should make a mod menu for the il2cpp Only baldis basics mods. Not mod menus for all decompiles.

**Comment by Fasguy** [comment]
In order for a mod to be made using IL2CPP, requires that the base game is decompiled, because IL2CPP is a compilation method.

**Comment by Kevinhthegdfan** [comment]
where do I add a script to make the mod menu appear when I look at the code?
