### ISSUE TITLE
Restore default settings

### ISSUE THREAD

**Issue by Fasguy** [Fasguy/BaldisBasicsModMenu-archive#28]
**Why do you need this feature?**
\-

**Describe the feature**
Restore default settings, without restarting the game

**Comment by TheWorks0710** [comment]
SeenWonderGabriel told me to on Steam Chat.

**Comment by ghost** [comment]
You know, i don't like exiting/restarting game of back to normal,

Me and TheWorks recommend to you add "Restore default settings", so clicking button that every mod menu setting will be off (almost like Baldi Basics Classic 1.4.3 Mod Menu)
