### ISSUE TITLE
Having the game's launcher disabled, doesn't initialize the audio patches for "Audio Vomit"

### ISSUE THREAD

**Issue by weegee12** [Fasguy/BaldisBasicsModMenu-archive#37]
When you enable the audio vomit and restart the scene, It still doesnt work. Any help?

**Comment by Fasguy** [comment]
Could you potentially record a video, showcasing the problem?
Also, what operating system do you use?

**Comment by weegee12** [comment]
Windows 10.

https://user-images.githubusercontent.com/108377469/217035353-0b522c58-a60e-4bc3-8f18-2e00821c5311.mp4

**Comment by Fasguy** [comment]
Thanks! I may have identified the issue.
