### ISSUE TITLE
Can't save presets

### ISSUE THREAD

**Issue by ObjNiya** [Fasguy/BaldisBasicsModMenu-archive#39]
**What's the Version of the game you're using?**
Baldi's Basics Classic Remastered V1.1

**What's the Version of the mod you're using?**
Mod Menu V1.0

**What Operating System are you using?**
Windows 11 64-bit

**Describe the bug**
When clicking the save button on the preset creator nothing happens, if i press cancel or go to saved presets nothing is there.

**Steps to reproduce the behavior**
I have no clue.

**Expected behavior**
That the save button saves the preset and that i can load it again later.

**Comment by Fasguy** [comment]
The presets list doesn't update automatically after saving a preset. Have you tried reloading the preset list with the dedicated button? Just closing and re-opening the presets menu doesn't reload the presets either.
