### ISSUE TITLE
Add NULL back into Baldi's Basics +

### ISSUE THREAD

**Issue by CodlngtheCoder** [Fasguy/BaldisBasicsModMenu-archive#47]
I Simply want this feature when the Plus mod menu comes out because i wanna see how nulls mechanics would work in plus and see how a bossfight would work in plus and it's just more challenging thing to do in plus since the maps are random and it will make plus a bit harder and funner (is that even a word) 

The Feature would work by clicking on a button inside the mod menu called "Null" and it would show a pop out next to the characters menu and in that pop out it would show most of the buttons inside the classic remastered mod menu for null and when you spawn null well he would act like how his AI would work in classic remastered and hopefully (Even though it will be a coding hell for you) you can enable the bossfight. There are two problems though. No.1 His AI is most (if isn't already no in plus) will be probably removed when the full version of plus is out. No.2 His Sprite is most likely (if it isn't in the game already) going to be removed from the full game as well. Anyways this is just a suggestion its gonna be very very very hard to do this.

**Comment by Fasguy** [comment]
This may be better suited for a seperate mod.

**Comment by CodlngtheCoder** [comment]
> This may be better suited for a seperate mod.

Would work like the BBCR Mod menu where its a plugin or a separate BepinEx Mod?

I Know it's unlikely i'm just asking btw

**Comment by Fasguy** [comment]
NULL itself should be completely seperate from the ModMenu. The ModMenu plugins system is designed to allow mods to work completely seperate, when the ModMenu isn't installed.
