### ISSUE TITLE
Ability Menu - big feature!

### ISSUE THREAD

**Issue by Filename99** [Fasguy/BaldisBasicsModMenu-archive#48]
**Why do you need this feature?**
While playing Baldi's Basics, I realized that the ability to customize character abilities would add a unique and exciting layer to the gameplay. By allowing customizable abilities, players would have more control over their experience, which would lead to more replayability and fun.

**Describe the feature**
In each character's mini-menu, there is a button called "Ability Menu". When you click it, it gives you a list of abilities you can choose for an NPC. I have come up with 6 abilities, but other users can request other custom ones.

- Teleportation (character teleports player to a random location on the map upon collision)

- Spit Gum (character spits gum at player)

- Wind Blow (character blows wind)

- Steal (character removes an item from the player's inventory upon collision)

- Jumprope (character triggers a jump rope mini-game upon collision)

- Blind (character will blind the player for a period of time upon collision)

What do you think?

**Comment by Fasguy** [comment]
The abilities of each character are deeply integrated into each character's logic. Stripping them is pretty much guaranteed to break stuff.
Maybe **Deception** fits your needs enough.
