### ISSUE TITLE
some 2 new features

### ISSUE THREAD

**Issue by ghost** [Fasguy/BaldisBasicsModMenu-archive#49]
**Why do you need this feature?**
needs 2 new features

**Describe the feature**
the first feature is 'add a notebook', you can collect a notebook easily without answering all questions by clicking 'add a notebook'
the second feature is 'disable yctp', you can disable the you can think pad by clicking 'disable yctp'

**Comment by Fasguy** [comment]
The **Add Notebook** feature is already planned for Plus and may get backported to Classic Remastered as well.
The **Disable YCTP** feature will be considered. This may get implemented as a dropdown, so you can choose whether or not all answers should be correct or wrong.

Also, for future reference: Please submit individual feature requests as individual issues. Combining them into one makes managing the issue unnecessarily complicated.

**Comment by ghost** [comment]
okeh
fun fact: this was the 2 features that was in oldsports mod menu then backported to fasguys mod menu
