### ISSUE TITLE
how to do it on mac

### ISSUE THREAD

**Issue by ghost** [Fasguy/BaldisBasicsModMenu-archive#52]
-

**Comment by Fasguy** [comment]
https://docs.bepinex.dev/articles/user_guide/installation/index.html?tabs=tabid-nix#installing-bepinex-1

Select the **Linux/macOS** section and follow along.

**Comment by ghost** [comment]
what is the root folder of it/

**Comment by Fasguy** [comment]
> what is the root folder of it/

That's explained on the site i sent you.
