### ISSUE TITLE
Chair goes through NULL

### ISSUE THREAD

**Issue by Benefonde** [Fasguy/BaldisBasicsModMenu-archive#54]
**What's the Version of the game you're using?**
Classic Remastered
1.1
**What's the Version of the mod you're using?**

1.1
**What Operating System are you using?**
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)
Windows 10 Pro 64 Bit

**Describe the bug**
Any chair or table you throw towards Null goes through him if you set his speed to lower than 1 [0,8 for example]

**Steps to reproduce the behavior**
Set Null's speed to 0,8 during the boss battle
Get a chair
Throw it at him

**Expected behavior**
Null gets damaged and speeds up

**Screenshots**

**Comment by Fasguy** [comment]
I can't reproduce the issue, could you send me a recording of this happening to you?

**Comment by Benefonde** [comment]
I would, but for no reason it just stopped happening. It might have been a one time issue, so I'll close the issue.
