### ISSUE TITLE
game get stuck at the "LOAD" screen

### ISSUE THREAD

**Issue by TripleGame** [Fasguy/BaldisBasicsModMenu-archive#55]
**What's the Version of the game you're using?**
1.1

**What's the Version of the mod you're using?**
v1.1.0

**What Operating System are you using?**
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)
Windows 10 64 Bit

**Describe the bug**
the game will get stuck at the LOAD menu. the menu where a bunch of heads of baldis are floating around.

**Steps to reproduce the behavior**
dang, i dont know? i came here to figure that out. i tried to reinstall it.. so, so much times but it keeps on not working.

**Expected behavior**
to enter the schoolhouse and start playing with the mod menu.

**Screenshots**

**Comment by TripleGame** [comment]
also, cant use the Mod Menu. pressing tab doesnt do anything.

**Comment by Fasguy** [comment]
Please upload your game's error log file here

It's the file "C:\Users\<your Windows user>\AppData\LocalLow\Basically Games\Baldi's Basics Classic Remastered\Player.log"

**Comment by TripleGame** [comment]
The whole file?
[Player.log](https://github.com/Fasguy/BaldisBasicsModMenu-archive/files/12334167/Player.log)

**Comment by TripleGame** [comment]
This?

**Comment by Fasguy** [comment]
The game fails to load the config file. Remove the config file (`C:\Users\<your Windows user>\AppData\LocalLow\Basically Games\Baldi's Basics Classic Remastered\Mods\Fasguy\ModMenu\config.json`) and try starting the game again.

**Comment by TripleGame** [comment]
okay, thanks!

**Comment by TripleGame** [comment]
I am gonna try it now.

**Comment by TripleGame** [comment]
It worked
