### ISSUE TITLE
Smol

### ISSUE THREAD

**Issue by AlsOnvARneR** [Fasguy/BaldisBasicsModMenu-archive#61]
i want to become smaller so it can be harder to collect items and it will be fun

**Comment by Fasguy** [comment]
A height modifier already exists in the player modifiers.

**Comment by AlsOnvARneR** [comment]
how do i make myself smaller, by using a - key, cause it dont work

**Comment by Fasguy** [comment]
Hotkeys are still planned and a completely seperate feature from this. You can already change your player height.

**Comment by AlsOnvARneR** [comment]
ooh ok
