### ISSUE TITLE
YCTP Behavior bug

### ISSUE THREAD

**Issue by Benefonde** [Fasguy/BaldisBasicsModMenu-archive#63]
**What's the Version of the game you're using?**
1.1, Classic Remastered

**What's the Version of the mod you're using?**
I'm using 1.2.0 of the mod.

**What Operating System are you using?**
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)
Windows 10 Pro 64bit

**Describe the bug**
Baldi hears every book you collect, even if you made it skip with all correct but impossible question.
Once you get to the end, you actually get the secret ending too.

**Steps to reproduce the behavior**
1. Go to either Classic or Party style
2. Set YCTP Behavior to Skip with all correct, except impossible question
3. Get the 3rd notebook or up.
4. Get to 7/7 and exit the school

**Expected behavior**
Baldi does not hear all of the notebooks that you collect after the 2nd one, and you get the normal ending instead.

**Screenshots**
Unsure if videos are allowed.

**Comment by Fasguy** [comment]
Videos are allowed

**Comment by Benefonde** [comment]
https://github.com/Fasguy/BaldisBasicsModMenu-archive/assets/80904546/f965d7f3-3955-49d7-a16a-78567bb72882
