### ISSUE TITLE
Null jumpscare sends you to title

### ISSUE THREAD

**Issue by Themegaballed** [Fasguy/BaldisBasicsModMenu-archive#64]
**Why do we need this feature?**
Can you add an option that makes it so that null wont crash the game if he catches you? is annoying having to reopen the game and set the values every time i lose (classic remastered, i am new so i dont know how to add labels yet)

**Comment by Fasguy** [comment]
This feature already exists, see https://github.com/Fasguy/BaldisBasicsModMenu-archive/issues/45#issuecomment-1475640514
