### ISSUE TITLE
Black screen on Android

### ISSUE THREAD

**Issue by chickennuggetsverygood** [Fasguy/BaldisBasicsModMenu-archive#65]
i have a black screen how do i fix this?
![Screenshot_20230916_031519_Baldi Classic Mod Menu 201](https://github.com/Fasguy/BaldisBasicsModMenu-archive/assets/145196596/065628db-0b4b-45be-b608-11c8a6723813)

**Comment by Fasguy** [comment]
This is a problem with Android 13, that i can't easily fix. My phone only got up to Android 9, running the game on Android Virtual Device x86 immediately crashes the game and running an armv8 instance of Android Virtual Device is currently not working beyond Android 9.

This will unfortunately be a `wontfix` issue for the time being.

**Comment by chickennuggetsverygood** [comment]
ok good to know i will wait for you to find a way

**Comment by Fasguy** [comment]
Apparently, enabling notifications for the app seems to fix the issue. Please try and see if that works for you.

**Comment by glira** [comment]
> This is a problem with Android 13, that i can't easily fix. My phone only got up to Android 9, running the game on Android Virtual Device x86 immediately crashes the game and running an armv8 instance of Android Virtual Device is currently not working beyond Android 9.
> 
> This will unfortunately be a `wontfix` issue for the time being.

is possible I try compile to Android 13 and I can make a pull request for this that you think? is to my son him only have 9 year lol

**Comment by Fasguy** [comment]
> > This is a problem with Android 13, that i can't easily fix. My phone only got up to Android 9, running the game on Android Virtual Device x86 immediately crashes the game and running an armv8 instance of Android Virtual Device is currently not working beyond Android 9.
> > This will unfortunately be a `wontfix` issue for the time being.
> 
> is possible I try compile to Android 13 and I can make a pull request for this that you think? is to my son him only have 9 year lol

If you wanna re-package it with appropriate permissions in place, then be my guest.
It's technically more of a minor annoyance than a proper issue, since enabling notifications for the app seems to fix the issue, as mentioned in my last comment.

**Comment by ayamfoyeng** [comment]
Same fix pls fasguy black screen
![Uploading Screenshot_20240420-000950.png…]()

**Comment by Fasguy** [comment]
@ayamfoyeng I sent you the link *to the fix*.

**Comment by Brohadabadcut** [comment]
uhh there is not a notification option for the app, I downloaded birthday bash and well I used that advice but there is no option for that
(my phone type is a galaxy A23 5G UW, phone version 14. that's what it said for the about phone)

**Comment by CoderMonkey1956** [comment]
> uhh there is not a notification option for the app, I downloaded birthday bash and well I used that advice but there is no option for that (my phone type is a galaxy A23 5G UW, phone version 14. that's what it said for the about phone)

What do you mean by this? The mod menu has not been released for Birthday Bash.

**Comment by Fasguy** [comment]
> > uhh there is not a notification option for the app, I downloaded birthday bash and well I used that advice but there is no option for that (my phone type is a galaxy A23 5G UW, phone version 14. that's what it said for the about phone)
> 
> What do you mean by this? The mod menu has not been released for Birthday Bash.

That is incorrect. Birthday Bash got a Mod Menu all the way back in 2019.

**Comment by CoderMonkey1956** [comment]
> > > uhh there is not a notification option for the app, I downloaded birthday bash and well I used that advice but there is no option for that (my phone type is a galaxy A23 5G UW, phone version 14. that's what it said for the about phone)
> > 
> > 
> > What do you mean by this? The mod menu has not been released for Birthday Bash.
> 
> That is incorrect. Birthday Bash got a Mod Menu all the way back in 2019.

For Android? I have the one for pc but wasn't aware there was even a birthday bash game for Android.
