### ISSUE TITLE
MIDI player and Audio Player + Map Editor

### ISSUE THREAD

**Issue by iamacoolpotato** [Fasguy/BaldisBasicsModMenu-archive#67]
**Why do you need this feature?**
I wanna have fun with vertex glitching, it's cool

**Describe the feature**
for midi, you can play any midi in the game like school, learn, intro
for audio, you can play gotta sweep's audio, all the audios and midis.
for map editor, basically you can edit the enviroment like the hallways and the walls and the floors

**Comment by iamacoolpotato** [comment]
oh and you can also play any midi sound

**Comment by Fasguy** [comment]
Please create seperate issues for each feature request.
