### ISSUE TITLE
CVXza iCHIpoxhncklw';x';nugetpototoc2444

### ISSUE THREAD

**Issue by caleb14472** [Fasguy/BaldisBasicsModMenu-archive#70]
**What's the VersionVERSUIB AXJB./.p; of thX.z/cme game you're using?**
sxxxxxxx
23cfgz
**What's the Version of the Waaaadsssmod you're using?**
Axxzx./.
2xffcvvv
**What Operating 52cz?><<ystem are you using?**
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)
wu10333333333

**Describe the bu111g**xh
A clear and concise description of what the bug is.chg
sahjxkl44xcmq23.cnugget

4444
**Steps to reproduce the behavior**
NNUGet.,/

**Expected behavior**
A cxclear and concise description of what you expected to happen.
b
222222
**Screensh44444ots**
3cmx,qqqqqqqqq333

**Comment by caleb14472** [comment]
chdren

**Comment by Fasguy** [comment]
How about no.
