### ISSUE TITLE
The menu works but the text is not showing up

### ISSUE THREAD

**Issue by CoderKid98799687** [Fasguy/BaldisBasicsModMenu-archive#75]
**What's the Version of the game you're using?**
BBCR 1.1

**What's the Version of the mod you're using?**
Latest

**What Operating System are you using?**
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)
Chronium Os (Debian)

**Describe the bug**
So basically My Ui is working but the text wont show up

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**

**Comment by Fasguy** [comment]
You still need to upload the Player.log file. You can just drag and drop it onto the textbox to upload it.

**Comment by CoderKid98799687** [comment]
I kinda deleted the thing but I remember you saying the text got trusticated

**Comment by Fasguy** [comment]
If you get the problem again, then please upload your Player.log here, i'll then re-open the issue.
