### ISSUE TITLE
Baldi's Basics Plus?!?!

### ISSUE THREAD

**Issue by Vectorr1** [Fasguy/BaldisBasicsModMenu-archive#80]
**What's the Version of the game you're using?** - 1.1

**What's the Version of the mod you're using?** - 1.2.0

**What Operating System are you using?** - Windows 10
Please provide the full Operating System name (example: Windows 10 Pro 64 Bit)

**Describe the bug** - I'm Playing BBCR, not BBP

**Steps to reproduce the behavior**

**Expected behavior**

**Screenshots**
![image](https://github.com/Fasguy/BaldisBasicsModMenu-archive/assets/152776882/7e25b867-16be-4fb0-ba22-8e512f1e107a)

**Comment by Fasguy** [comment]
This was already fixed in a silent re-upload of v1.2.0. It's a simple mistake that popped up, due to the shared codebase, but has no effect on the functionality of the ModMenu.
