### ISSUE TITLE
character can see through walls toggle

### ISSUE THREAD

**Issue by AndrewScripter587** [Fasguy/BaldisBasicsModMenu-archive#84]
This is for BBCR mod menu

**Why do you need this feature?**
It would make for some fun challenges where you cannot hide from some characters

**Describe the feature**
this would be a toggle under most character modifiers
enabling the toggle will make all instances of the character see through walls, dirty chalk eraser dust, and fog from the fog event.
for example, if the toggle is enabled for Baldi, Baldi would be able to see the player through walls, dirty chalk eraser dust, and fog, and therefore know where the player is at all times due to baldi having an infinite view range.
another example is if the toggle is enabled for Playtime, Playtime would be able to see through walls, dirty chalk eraser dust, and fog, but not know where the player is at all times because Playtime has a limited view range, and Playtime would still respect the view range.
you could also make Principal of the Thing work like in the old Baldi's Basics, where he always knows where you are if you get a detention and will constantly chase you even if you leave Principal of the Thing's view..
this would likely not work with Chalkles, because Chalkles works differently than the other characters.

**Comment by AndrewScripter587** [comment]
just found out that this is pretty much just a duplicate of #68

**Comment by dave41413** [comment]
hey andrew

**Comment by AndrewScripter587** [comment]
Yeah?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
